{
 "title": "ADSB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "expr": "dump1090_alt_baro{flight!=\"\"}",
     "legendFormat": "{{flight}}"
    }
   ]
  },
  {
   "title": "Ground Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "dump1090_gs{flight!=\"\"}",
     "legendFormat": "{{flight}}"
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "dump1090_messages{flight!=\"\"}",
     "legendFormat": "{{flight}}"
    }
   ]
  }
 ]
}